version: "3.7"

services:
  server:
    container_name: server
    environment:
      - SERVER_PORT
      - NODE_ENV
      - MAX_SYMBOLS_PER_OBJECT
      - MAX_OPTIONAL_PROPERTIES
      - MIN_PASSWORD_LENGTH
      - JWT_SECRET_KEY
      - JWT_EXPIRE_TIME
      - JWT_REFRESH_SECRET_KEY
      - JWT_REFRESH_EXPIRE_TIME
    build:
      context: ./backend/
      target: development
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: npm start
    env_file:
      - .env
    links:
      - mongo
    depends_on:
      - mongo
      - client

  client:
    container_name: client
    build:
      context: ./frontend/
      target: development
    command: npm start
    env_file:
      - .env
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    stdin_open: true

  mongo:
    image: mongo:latest
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}